"""add indexes to sitemap table

Revision ID: 1d216b5e6c90
Revises: 9995dda15386
Create Date: 2025-09-26 13:24:45.231269

"""

# revision identifiers, used by Alembic.
revision = '1d216b5e6c90'
down_revision = '9995dda15386'

from alembic import op
import sqlalchemy as sa

                               


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add sitemap table indexes
    op.create_index(op.f('ix_sitemap_bibcode'), 'sitemap', ['bibcode'], unique=True)
    op.create_index(op.f('ix_sitemap_sitemap_filename'), 'sitemap', ['sitemap_filename'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sitemap_sitemap_filename'), table_name='sitemap')
    op.drop_index(op.f('ix_sitemap_bibcode'), table_name='sitemap')
    # ### end Alembic commands ###
