"""Added BoostFactors table

Revision ID: 6973dd1d9f2b
Revises: 2d2af8a9c996
Create Date: 2024-11-20 18:23:26.770835

"""

# revision identifiers, used by Alembic.
revision = '6973dd1d9f2b'
down_revision = '2d2af8a9c996'

from alembic import op
import sqlalchemy as sa


def upgrade():
    #with app.app_context() as c:
    #   db.session.add(Model())
    #   db.session.commit()
        
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boostfactors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('bibcode', sa.String(length=255), nullable=True),
    sa.Column('doctype_boost', sa.Float(), nullable=True),
    sa.Column('cite_boost', sa.Float(), nullable=True),
    sa.Column('recency_boost', sa.Float(), nullable=True),
    sa.Column('refereed_boost', sa.Float(), nullable=True),
    sa.Column('cite_boost_astro', sa.Float(), nullable=True),
    sa.Column('cite_boost_geo', sa.Float(), nullable=True),
    sa.Column('cite_boost_planetary', sa.Float(), nullable=True),
    sa.Column('cite_boost_physics', sa.Float(), nullable=True),
    sa.Column('cite_boost_general', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boostfactors')
    # ### end Alembic commands ###
