"""Added boost column in RecordsDB

Revision ID: 6f2dfbcd14b4
Revises: 5b6eb3fb2de0
Create Date: 2025-08-21 20:11:47.909911

"""

# revision identifiers, used by Alembic.
revision = '6f2dfbcd14b4'
down_revision = '5b6eb3fb2de0'

from alembic import op
import sqlalchemy as sa
import adsmp

                               


def upgrade():
    #with app.app_context() as c:
    #   db.session.add(Model())
    #   db.session.commit()
        
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('boost_factors', sa.Text(), nullable=True))
    op.add_column('records', sa.Column('boost_factors_updated', adsmp.models.UTCDateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'boost_factors_updated')
    op.drop_column('records', 'boost_factors')
    # ### end Alembic commands ###
