"""create sitemap table

Revision ID: 8ab1dc58a20b
Revises: 2d2af8a9c996
Create Date: 2025-07-28 13:37:32.063260

"""

# revision identifiers, used by Alembic.
revision = '8ab1dc58a20b'
down_revision = '2d2af8a9c996'

from alembic import op
import sqlalchemy as sa
import adsmp.models

                               


def upgrade():
    #with app.app_context() as c:
    #   db.session.add(Model())
    #   db.session.commit()
        
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitemap',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=False, autoincrement=True),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('bibcode', sa.String(length=255), nullable=False),
    sa.Column('scix_id', sa.String(length=255), nullable=True),
    sa.Column('bib_data_updated', adsmp.models.UTCDateTime(), nullable=True),
    sa.Column('sitemap_filename', sa.String(length=255), nullable=True),
    sa.Column('filename_lastmoddate', adsmp.models.UTCDateTime(), nullable=True),
    sa.Column('update_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitemap')
    # ### end Alembic commands ###
