"""Added sitemap table

Revision ID: ae542e1ad8eb
Revises: 2d2af8a9c996
Create Date: 2024-05-22 19:44:23.053421

"""

# revision identifiers, used by Alembic.
revision = 'ae542e1ad8eb'
down_revision = '2d2af8a9c996'

from alembic import op
import sqlalchemy as sa
import adsmp


def upgrade():
    #with app.app_context() as c:
    #   db.session.add(Model())
    #   db.session.commit()
        
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitemap',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=True),
    sa.Column('bibcode', sa.String(length=255), nullable=True),
    sa.Column('bib_data_updated', adsmp.models.UTCDateTime(), nullable=True),
    sa.Column('sitemap_filename', sa.String(length=255), nullable=True),
    sa.Column('filename_lastmoddate', adsmp.models.UTCDateTime(), nullable=True),
    sa.Column('update_flag', sa.Boolean(), nullable=True),    
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitemap')
    # ### end Alembic commands ###
